version: '3.9'
services:
  aivisspeech:
    image: ghcr.io/aivis-project/aivisspeech-engine:nvidia-latest@sha256:581c9d0881c0642c3b5a0a323ccb138b11ca92d04009d4d90fbf2877ebc29e70
    hostname: aivisspeech
    container_name: aivisspeech__aivisspeech
    restart: unless-stopped

    networks:
      - default

    volumes:
      - type: bind
        source: ./AivisSpeech-Engine
        target: /home/user/.local/share/AivisSpeech-Engine-Dev

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              # Fix for docker-ce 27.3.x bugs.
              # refs:
              #   https://x.com/yanorei32/status/1840455188928405554
              #   https://github.com/moby/moby/pull/48483
              #   https://docs.docker.com/compose/how-tos/gpu-support/
              count: all
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2026.7.3-amd64@sha256:b392761b711c0e5649d9b64e1fc9a10ba0563fa3e712ed7c26bde5cc1fbe9059
    hostname: cloudflared
    container_name: aivisspeech__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: aivisspeech__default
