version: '3.9'
services:
  aivisspeech:
    image: ghcr.io/aivis-project/aivisspeech-engine:nvidia-latest@sha256:d999db322218128111bccf0fe8a45648bc9eca4d783282a5093e6f5d2938a50b
    hostname: aivisspeech
    container_name: aivisspeech__aivisspeech
    restart: unless-stopped

    networks:
      - default

    volumes:
      - type: bind
        source: ./AivisSpeech-Engine
        target: /home/user/.local/share/AivisSpeech-Engine-Dev

    deploy:
      resources:
        limits:
          memory: 16g
        reservations:
          devices:
            - driver: nvidia
              # Fix for docker-ce 27.3.x bugs.
              # refs:
              #   https://x.com/yanorei32/status/1840455188928405554
              #   https://github.com/moby/moby/pull/48483
              #   https://docs.docker.com/compose/how-tos/gpu-support/
              count: all
              capabilities: [gpu]

  cloudflared:
    image: cloudflare/cloudflared:2026.8.3-amd64@sha256:9be48e4b4e996da851bf78f7782bfab150dd4d8889e469d004802e7d7afb63b1
    hostname: cloudflared
    container_name: aivisspeech__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: aivisspeech__default
